param(
    [switch]$Stage
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$imgRoot  = [IO.Path]::GetFullPath((Join-Path $repoRoot 'img'))
$gitDir   = Join-Path $repoRoot '.git'
$rawDir   = Join-Path $repoRoot 'img\raw'

$extensions = @('.html', '.xhtml', '.css', '.js', '.md')

# Captures img/foo.png, ./img/foo.png, ../img/foo.png, etc.
$pattern = '(?i)(?<path>(?:\.\.?[\\/])*(?:img)[\\/][^"''<>\s\)\]]+)'

$used   = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::Ordinal
)

$errors = [System.Collections.Generic.List[string]]::new()

$sourceFiles = Get-ChildItem -Path $repoRoot -Recurse -File |
    Where-Object {
        $extensions -contains $_.Extension.ToLowerInvariant() -and
        -not $_.FullName.StartsWith($gitDir, [StringComparison]::OrdinalIgnoreCase) -and
        -not $_.FullName.StartsWith($rawDir, [StringComparison]::OrdinalIgnoreCase) -and
        -not $_.FullName.Contains('.marker-preview\')
    }

foreach ($file in $sourceFiles) {

    $content = Get-Content .\index.html -Raw

    $content = $content `
        -replace 'img/RI-karama\.png', 'img/RI-karama-big.png' `
        -replace 'img/CH-logo\.png', 'img/CH-logo-big.png' `
        -replace 'img/ch-logo\.png', 'img/CH-logo-big.png' `
        -replace 'img/MO-karama\.png', 'img/MO-karama-big.png'

    Set-Content .\index.html $content

    foreach ($match in [regex]::Matches($content, $pattern)) {

        $ref = $match.Groups['path'].Value
        $ref = $ref -replace '[?#].*$', ''

        $nativeRef = $ref -replace '/', '\'

        try {
            $resolved = [IO.Path]::GetFullPath(
                (Join-Path $file.DirectoryName $nativeRef)
            )
        }
        catch {
            $errors.Add("$($file.FullName): invalid image path '$ref'")
            continue
        }

        # References must resolve inside the project's root img directory.
        $imgPrefix = $imgRoot.TrimEnd('\') + '\'

        if (-not $resolved.StartsWith(
            $imgPrefix,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            $errors.Add(
                "$($file.FullName): '$ref' does not resolve inside root img/"
            )
            continue
        }

        if (-not (Test-Path -LiteralPath $resolved -PathType Leaf)) {
            $errors.Add(
                "$($file.FullName): referenced image does not exist: '$ref'"
            )
            continue
        }

        $item = Get-Item -LiteralPath $resolved

        $gitPath = $item.FullName.Substring($repoRoot.Length)
        $gitPath = $gitPath -replace '^[\\/]+', ''
        $gitPath = $gitPath -replace '\\', '/'

        if ($gitPath.StartsWith(
            'img/raw/',
            [StringComparison]::OrdinalIgnoreCase
        )) {
            $errors.Add(
                "$($file.FullName): '$ref' points into img/raw/, which is never versioned"
            )
            continue
        }

        # Catch case errors that work on Windows but would break on Linux/GitHub.
        $refNormalized = $ref -replace '\\', '/'
        $pos = $refNormalized.ToLowerInvariant().IndexOf('img/')

        if ($pos -ge 0) {
            $refImgPath = $refNormalized.Substring($pos)

            if ($refImgPath -cne $gitPath) {
                $errors.Add(
                    "$($file.FullName): case/path mismatch '$refImgPath' -> actual '$gitPath'"
                )
                continue
            }
        }

        [void]$used.Add($gitPath)
    }
}

if ($errors.Count -gt 0) {
    Write-Host ""
    Write-Host "BROKEN IMAGE REFERENCES:" -ForegroundColor Red

    foreach ($error in $errors) {
        Write-Host "  - $error" -ForegroundColor Red
    }

    Write-Host ""
    exit 1
}

# ----------------------------------------------------------------------
# Regenerate managed .gitignore section
# ----------------------------------------------------------------------

$gitignore = Join-Path $repoRoot '.gitignore'

$beginMarker = '# BEGIN AUTO-USED-IMAGES'
$endMarker   = '# END AUTO-USED-IMAGES'

$managedLines = @(
    $beginMarker
    '# Generated by scripts/update-image-gitignore.ps1'
    '# Do not edit this section manually.'
    'img/*'
    'img/raw/'
)

$managedLines += @($used) |
    Sort-Object |
    ForEach-Object { "!$_" }

$managedLines += $endMarker

$newBlock = $managedLines -join [Environment]::NewLine

if (Test-Path $gitignore) {
    $oldContent = [IO.File]::ReadAllText($gitignore)
}
else {
    $oldContent = ''
}

$blockPattern =
    '(?s)' +
    [regex]::Escape($beginMarker) +
    '.*?' +
    [regex]::Escape($endMarker)

if ([regex]::IsMatch($oldContent, $blockPattern)) {
    $newContent = [regex]::Replace(
        $oldContent,
        $blockPattern,
        [System.Text.RegularExpressions.MatchEvaluator]{
            param($m)
            $newBlock
        }
    )
}
else {
    if ($oldContent.Length -gt 0 -and -not $oldContent.EndsWith("`n")) {
        $oldContent += [Environment]::NewLine
    }

    $newContent =
        $oldContent +
        [Environment]::NewLine +
        $newBlock +
        [Environment]::NewLine
}

if ($newContent -ne $oldContent) {
    [IO.File]::WriteAllText(
        $gitignore,
        $newContent,
        [Text.UTF8Encoding]::new($false)
    )
}

# ----------------------------------------------------------------------
# Optional Git staging, used by pre-commit hook
# ----------------------------------------------------------------------

if ($Stage) {

    Push-Location $repoRoot

    try {
        git add -- .gitignore

        foreach ($path in (@($used) | Sort-Object)) {
            git add -- $path
        }

        # Remove images from Git if they stopped being referenced.
        # --cached keeps the physical files on disk.
        $trackedImages = @(git ls-files -- 'img/*')

        foreach ($path in $trackedImages) {

            $normalized = $path -replace '\\', '/'

            $mustRemove =
                $normalized.StartsWith(
                    'img/raw/',
                    [StringComparison]::OrdinalIgnoreCase
                ) -or
                -not $used.Contains($normalized)

            if ($mustRemove) {
                git rm --cached -f --quiet -- $path
            }
        }
    }
    finally {
        Pop-Location
    }
}

Write-Host ""
Write-Host "Images referenced and allowed in Git: $($used.Count)"
Write-Host ""

@($used) |
    Sort-Object |
    ForEach-Object { Write-Host "  $_" }

Write-Host ""